ALTER TABLE orders
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;

UPDATE orders
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

ALTER TABLE orders
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE orders
    ALTER COLUMN created_at SET NOT NULL;